# Generated by Django 4.2.27 on 2026-01-08 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remote_support', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='remotesupportsession',
            name='anydesk_id',
            field=models.CharField(default='N/A', help_text="User's AnyDesk ID for remote connection", max_length=50),
            preserve_default=False,
        ),
    ]
