# Generated by Django 4.2.27 on 2026-01-08 22:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('remote_support', '0002_remotesupportsession_anydesk_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='remotesupportsession',
            name='is_voice_active',
            field=models.BooleanField(default=False, help_text='Whether voice-to-text features are currently active'),
        ),
        migrations.CreateModel(
            name='VoiceTranscript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_transcripts', to='remote_support.remotesupportsession')),
                ('speaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
