# Generated by Django 6.0 on 2025-12-18 22:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(editable=False, max_length=20, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('impact', models.IntegerField(choices=[(1, '1 - High (Enterprise-wide)'), (2, '2 - Medium (Department-wide)'), (3, '3 - Low (Individual user)')], default=3)),
                ('urgency', models.IntegerField(choices=[(1, '1 - High (Critical business function)'), (2, '2 - Medium (Normal business function)'), (3, '3 - Low (Non-critical function)')], default=3)),
                ('priority', models.IntegerField(choices=[(1, 'P1 - Critical'), (2, 'P2 - High'), (3, 'P3 - Medium'), (4, 'P4 - Low')], default=4, editable=False)),
                ('state', models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('on_hold', 'On Hold'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='new', max_length=20)),
                ('due_date', models.DateTimeField(blank=True, editable=False, null=True)),
                ('sla_breached', models.BooleanField(default=False)),
                ('resolution_notes', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, help_text='IT Staff assigned to resolve', limit_choices_to={'role__in': ['it_support', 'admin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_incidents', to=settings.AUTH_USER_MODEL)),
                ('caller', models.ForeignKey(help_text='User who reported the incident', on_delete=django.db.models.deletion.CASCADE, related_name='reported_incidents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Incident',
                'verbose_name_plural': 'Incidents',
                'ordering': ['priority', '-created_at'],
            },
        ),
    ]
