# Generated by Django 4.2.27 on 2025-12-19 00:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incident',
            options={'ordering': [models.Case(models.When(state='resolved', then=1), models.When(state='closed', then=2), default=0, output_field=models.IntegerField()), 'priority', '-created_at'], 'verbose_name': 'Incident', 'verbose_name_plural': 'Incidents'},
        ),
        migrations.AddField(
            model_name='incident',
            name='location',
            field=models.CharField(blank=True, help_text="Caller's location", max_length=200),
        ),
        migrations.AlterField(
            model_name='incident',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='IT Staff assigned to resolve', limit_choices_to={'role__in': ['it_support', 'technician', 'admin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_incidents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='incident',
            name='state',
            field=models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('on_hold', 'On Hold'), ('needs_help', 'Needs Advanced Help'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='new', max_length=20),
        ),
    ]
