# Generated by Django 4.2.27 on 2025-12-19 01:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('laptop', 'Laptop'), ('desktop', 'Desktop'), ('monitor', 'Monitor'), ('phone', 'Phone'), ('printer', 'Printer'), ('network', 'Network Equipment'), ('software', 'Software License'), ('other', 'Other')], max_length=20, unique=True)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Asset Inventory',
                'verbose_name_plural': 'Asset Inventory',
                'ordering': ['item_type'],
            },
        ),
        migrations.AddField(
            model_name='asset',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_assets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('in_stock', 'In Stock'), ('assigned', 'Assigned'), ('under_review', 'Under Review'), ('declined', 'Declined'), ('in_repair', 'In Repair'), ('retired', 'Retired')], default='in_stock', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('staff', 'Staff'), ('it_support', 'IT Support'), ('technician', 'Technician'), ('manager', 'Manager'), ('admin', 'Administrator')], default='staff', max_length=20),
        ),
    ]
