# Generated by Django 4.2.27 on 2025-12-19 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0003_alter_asset_serial_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='code',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
