# Generated by Django 4.2.27 on 2026-01-01 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0004_alter_department_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetinventory',
            name='display_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_type',
            field=models.CharField(choices=[('laptop', 'Laptop'), ('desktop', 'Desktop'), ('monitor', 'Monitor'), ('phone', 'Phone'), ('printer', 'Printer'), ('network', 'Network Equipment'), ('software', 'Software License')], max_length=20),
        ),
        migrations.AlterField(
            model_name='assetinventory',
            name='item_type',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
