# Generated by Django 4.2.27 on 2026-01-02 01:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('incident_assigned', 'Incident Assigned'), ('incident_resolved', 'Incident Resolved'), ('incident_escalated', 'Incident Escalated'), ('sla_warning', 'SLA Warning'), ('sla_breached', 'SLA Breached'), ('request_submitted', 'Request Submitted'), ('request_approved', 'Request Approved'), ('request_rejected', 'Request Rejected'), ('request_completed', 'Request Completed'), ('asset_assigned', 'Asset Assigned'), ('general', 'General')], default='general', max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('link', models.CharField(blank=True, max_length=500)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
