# Generated by Django 4.2.27 on 2025-12-19 00:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('service_requests', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicerequest',
            options={'ordering': [models.Case(models.When(state='completed', then=1), default=0, output_field=models.IntegerField()), '-created_at'], 'verbose_name': 'Service Request', 'verbose_name_plural': 'Service Requests'},
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='location',
            field=models.CharField(blank=True, help_text="Requester's location", max_length=200),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='assigned_to',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['it_support', 'technician', 'admin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='state',
            field=models.CharField(choices=[('draft', 'Draft'), ('awaiting_approval', 'Awaiting Approval'), ('approved', 'Approved'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('needs_help', 'Needs Advanced Help'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='draft', max_length=20),
        ),
    ]
