# Generated by Django 4.2.27 on 2025-12-19 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0004_alter_department_code'),
        ('service_requests', '0002_alter_servicerequest_options_servicerequest_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='allocated_asset',
            field=models.ForeignKey(blank=True, help_text='Asset allocated for this request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_requests', to='cmdb.asset'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='requested_asset_type',
            field=models.CharField(blank=True, choices=[], help_text='Type of asset being requested (for hardware requests)', max_length=20, null=True),
        ),
    ]
